version: '3'
services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports: 
      - 3000:3000
    volumes:
      - ./frontend/src:/frontend/src
    container_name: frontend-dev
    depends_on:
      - server
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - 5000:5000
      - 8000:8000
    volumes:
      - ./server/src:/server/src
    container_name: server-dev