name: PyLint Runner

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - gh-action-lint
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r server/requirements.txt
        pip install pylint
    - name: Run Pylint
      run: |
        pylint ./server
